name: CI/CD Pipeline

on:
  push:
    branches:
      - KAN-4-refactor-testing
  pull_request:
    branches:
      - KAN-4-refactor-testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "docker-compose.yml" 
          up-flags: "--build -d" 
          down-flags: "--volumes" 
          test-container: "business-web"  
          test-command: |
            # Wait for PostgreSQL to be ready
            until pg_isready -U postgres -h business-db; do
              echo "Waiting for PostgreSQL..."
              sleep 2
            done;
            
            # Run yoyo migrations
            yoyo apply artifacts/migrations;
            
            # Run tests with pytest
            pytest .